baseURL: 'https://vitsing.github.io/'
languageCode: 'en-us'
title: 'Ming Dong - Academic Homepage'

module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5

params:
  author: 'Ming Dong'
  description: 'Academic homepage of Ming Dong, faculty member at CCNU'
  favicon: 'favicon.ico'
  
menu:
  main:
    - name: 'Home'
      url: '/'
      weight: 1
    - name: 'Publications'
      url: '#publications'
      weight: 2
    - name: 'Teaching'
      url: '#teaching'
      weight: 3
    - name: 'Contact'
      url: '#contact'
      weight: 4 