# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  title: Ming Dong's Academic Homepage
  params:
    description: Academic homepage of Ming Dong
  menu:
    main:
      - name: About
        url: '#about'
        weight: 10
      - name: Projects
        url: '#projects'
        weight: 20
      - name: Publications
        url: '#publications'
        weight: 30
      - name: Teaching
        url: '#teaching'
        weight: 40
      - name: Service
        url: '#service'
        weight: 50
      - name: Contact
        url: '#contact'
        weight: 60

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
